#add_newline = false

[line_break]
disabled = true


[character]
success_symbol = "[➜](bold green) "
vicmd_symbol = "[➜](bold yellow) "
error_symbol = "[➜](bold red) "

#[character]
#success_symbol = "[✗](bold yellow)"
#vicmd_symbol = "[✗](bold yellow)"
#error_symbol = "[✗](bold red)"
